- hosts: localhost
  roles:
    - arch-root

    # TBD - create a role for specific hardware
    # That role will include specific tasks from
    # a hardware role
    # - zbook

  vars_prompt:
    - name: "archlinux_user_name"
      prompt: "Enter your username"
      private: no
    - name: "archlinux_user_email"
      prompt: "Enter your email (for gitconfig)"
      private: no
    - name: "archlinux_user_password"
      prompt: "Enter your password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 14
