- name: install utilities (browsers, file explorer, image viewer, etc) (from repos)
  pacman: name={{ item }} state=present
  with_items:
    - firefox
    - thunar
    - thunar-volman
    - thunar-archive-plugin
    - atom
    - feh
    - remmina # TBD, maybe replace with rdesktop
    - xsel
    - xbindkeys
    - volumeicon
  become: yes

- name: install utilities (browsers, file explorer, image viewer, etc) (from aur)
  command: "yaourt -S {{ item }} --noconfirm"
  with_items:
    - cmst
    - remmina-plugin-rdesktop # TBD, irrelevant if we use rdesktop
    - volnoti
