---
- name: clone package-query
  git:
    accept_hostkey: yes
    repo: "{{ package_query_git }}"
    dest: ~/package-query
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: clone yaourt
  git:
    accept_hostkey: yes
    repo: "{{ yaourt_git }}"
    dest: ~/yaourt
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: makepkg package-query
  shell: 'cd ~/package-query && makepkg --noconfirm -f -s'
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: install package-query
  shell: "pacman -U /home/{{ archlinux_user_name }}/package-query/*.pkg.tar.xz --noconfirm"
  become: yes

- name: makepkg yaourt
  shell: 'cd ~/yaourt && makepkg --noconfirm -f -s'
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: install yaourt
  shell: "pacman -U /home/{{ archlinux_user_name }}/yaourt/*.pkg.tar.xz --noconfirm"
  become: yes

- name: cleanup package-query and yaourt
  file: path={{ item }} state=absent
  with_items:
    - '~/package-query'
    - '~/yaourt'
  become: yes
  become_user: "{{ archlinux_user_name }}"

# now that I have yaourt, I can also install cower
- name: add cower key
  shell: "gpg --keyserver pgp.mit.edu --recv-keys {{ cower_key_id }}"
  become: yes
  become_user: "{{ archlinux_user_name }}"

- name: install cower
  command: "yaourt -S cower --noconfirm"
  become: yes
  become_user: "{{ archlinux_user_name }}"

