---
- name: install zsh
  pacman: name={{ item }} state=present
  with_items:
    - zsh
    - zsh-completions
  become: yes

- name: change default shell to zsh
  user: name={{ item }} shell=/usr/bin/zsh
  with_items:
    - root
    - "{{ archlinux_user_name }}"
  become: yes

- name: install oh-my-zsh
  git:
    accept_hostkey: yes
    repo: "{{ oh_my_zsh_git }}"
    dest: ~/.oh-my-zsh

- name: stow zsh config
  command: "stow -d ~/dotfiles -t ~/ zsh"
