---
- name: install urxvt and extras
  pacman: name={{ item }} state=present
  with_items:
    - rxvt-unicode
    - tmux
  become: yes

- name: stow urxvt
  command: "stow -d ~/dotfiles -t ~/ urxvt"

- name: set urxvt icon
  shell: "echo \"Urxvt*iconFile: /home/{{ archlinux_user_name }}/.local/share/icons/hicolor/128x128/apps/urxvt.png\" > ~/.config/Xresources/urxvt-icon"
